#!/bin/bash -e

ACCOUNT=zver
REPO=zver-linux-utils

tmpdir=$(mktemp -d /tmp/$REPO.XXXXXX)
trap 'rm -rf "$tmpdir"' EXIT

git clone https://github.com/$ACCOUNT/$REPO.git $tmpdir
cd "$tmpdir"

ls
sudo ./install
