#!/bin/bash
# Tests connectivity and throughput to a list of SSH jump hosts, selects the
# best-performing host, and creates a local SSH port-forwarding tunnel to the
# target server through the selected jump host.
#
# Example config file /etc/ssh-port-forwarding:
#
#SSH_JUMP_KEY_FILE=/etc/key2
#SSH_JUMP_USER=user2
#SSH_JUMP_HOSTS="192.168.10.1,192.168.10.2"
#SSH_KEY_FILE=/etc/key1
#SSH_USER=user1
#SSH_HOST=1.1.1.1
#LOCAL_PORT=12080
#REMOTE_PORT=2080


set -euo pipefail

source /etc/${0##*/}.conf

BEST_HOST=`check-ssh-speed -c 1 -n 10 -l 32 -t 10 -u $SSH_JUMP_USER -i  $SSH_JUMP_KEY_FILE \
        $SSH_JUMP_HOSTS \
        | grep OK | LANG=C sort -k3,3 -nr | head -n1 | cut -d ' ' -f2`

if [[ -z "$BEST_HOST" ]]; then
        echo "Can not connect to any HOST" >&2
        exit 1
fi

echo "New best host for ssh jump host: $BEST_HOST"

ssh -N \
        -o "ProxyCommand=ssh \
                -o ExitOnForwardFailure=yes \
                -o ServerAliveInterval=60 \
                -o StrictHostKeyChecking=no \
                -o UserKnownHostsFile=/dev/null \
                -i $SSH_JUMP_KEY_FILE -W %h:%p $SSH_JUMP_USER@$BEST_HOST" \
        -o ExitOnForwardFailure=yes \
        -o ServerAliveInterval=60 \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -i $SSH_KEY_FILE \
        $SSH_USER@$SSH_HOST \
        -L $LOCAL_PORT:$SSH_HOST:$REMOTE_PORT
