#!/bin/bash
# See ssh-port-forwarding.README.md for details

set -euo pipefail

source /etc/${0##*/}.conf

BEST_HOST=`check-ssh-speed -c 1 -n 10 -l 32 -t 10 -u $SSH_JUMP_USER -i  $SSH_JUMP_KEY_FILE \
        $SSH_JUMP_HOSTS \
        | grep OK | LANG=C sort -k3,3 -nr | head -n1 | cut -d ' ' -f2`

if [[ -z "$BEST_HOST" ]]; then
        echo "Can not connect to any HOST" >&2
        exit 1
fi

echo "New best host for ssh jump host: $BEST_HOST"

ssh -N \
        -o "ProxyCommand=ssh \
                -o ExitOnForwardFailure=yes \
                -o ServerAliveInterval=60 \
                -o StrictHostKeyChecking=no \
                -o UserKnownHostsFile=/dev/null \
                -i $SSH_JUMP_KEY_FILE -W %h:%p $SSH_JUMP_USER@$BEST_HOST" \
        -o ExitOnForwardFailure=yes \
        -o ServerAliveInterval=60 \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -i $SSH_KEY_FILE \
        $SSH_USER@$SSH_HOST \
        -L $LOCAL_PORT:$SSH_HOST:$REMOTE_PORT \
        2>&1 | egrep -v 'Warning: Permanently added .* to the list of known hosts'
